
# =================================================
# config.yaml  —  Enhanced hyper‑parameters
# =================================================
img_size: 128 # 圖像大小
batch_size: 96 # 批次大小
n_epochs: 100 # 訓練 epoch 數量
lr: 0.0002 # 學習率
beta1: 0.5 # Adam 優化器參數 beta1
beta2: 0.999 # Adam 優化器參數 beta2

# Enhanced loss configuration
lambda_l1: 0.05 # L1 損失權重 (進一步降低)
lambda_iou: 2.0 # IoU/GIoU 損失權重 (增加重要性)
use_giou: true # 是否使用 GIoU 而不是 IoU
use_hybrid_loss: true # 是否使用混合損失函數

spectral_norm: true # 是否使用譜範數
delta_scale: 0.3 # delta 縮放因子 (降低以減少過度校正)
generator_type: "simple" # 生成器類型: "unet" 或 "simple"
early_stop: # 早停設定
  patience: 15 # 早停耐心值 (增加耐心)
  min_delta: 5.0e-5 # 早停最小 delta (降低閾值)
train_split: 0.9 # 訓練集分割比例
val_split: 0.1 # 驗證集分割比例
amp: true # 是否使用自動混合精度
save_dir: runs/exp # 模型儲存目錄
seed: 42 # 隨機種子
d_train_ratio: 1 # 每 N 個批次訓練一次判別器 (提高訓練頻率)
iou_threshold: 0.3 # IoU 閾值用於匹配預測框與真實框
data_dir: ../datasets/500_100_100/cgan # 資料集根目錄路徑


