
# =================================================
# config.yaml  —  Default hyper‑parameters
# =================================================
img_size: 256 # 圖像大小
batch_size: 32 # 批次大小
n_epochs: 120 # 訓練 epoch 數量
lr: 0.0002 # 學習率
beta1: 0.5 # Adam 優化器參數 beta1
beta2: 0.999 # Adam 優化器參數 beta2
lambda_l1: 1000 # L1 損失權重
spectral_norm: true # 是否使用譜範數
delta_scale: 0.25 # delta 縮放因子
early_stop: # 早停設定
  patience: 10 # 早停耐心值
  min_delta: 1.0e-4 # 早停最小 delta
train_split: 0.9 # 訓練集分割比例
val_split: 0.1 # 驗證集分割比例
amp: true # 是否使用自動混合精度
save_dir: runs/exp # 模型儲存目錄
seed: 42 # 隨機種子
d_train_ratio: 2 # 每 N 個批次訓練一次判別器
iou_threshold: 0.3 # IoU 閾值用於匹配預測框與真實框
data_dir: datasets/500_100_100/cgan # 資料集根目錄路徑


